version: '3.3'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_URL: jdbc:mysql://mysql/ssd_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
  admin-back-end:
    build:
      context: ./Admin-back-end
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_URL: jdbc:mysql://mysql/ssd_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - back-end
  front-end:
    build:
      context: ./front-end  
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - back-end
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
  vault:
    hostname: vault
    container_name: vault
    restart: on-failure
    image: vault:1.13.3
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl


  vault-init:
    container_name: vault-init
    image: vault:1.13.3
    restart: on-failure
    environment:
      VAULT_ADDR: "http://vault:8200"
    volumes:
      - ./unseal-vault.sh:/unseal-vault.sh
    entrypoint: sh -c "/unseal-vault.sh"
    depends_on:
      - vault
  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: mykeycloak
    restart: on-failure
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_FRONTEND_URL=https://bandiunina.it/auth
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=${DB_KEYCLOAK_PASSWORD} 
      - KEYCLOAK_IMPORT=/tmp/realm.json
    volumes:
      - ./realm.json:/tmp/realm.json
      - ./keycloak-theme/login.ftl:/opt/jboss/keycloak/themes/base/login/login.ftl
      - ./keycloak-theme/terms.ftl:/opt/jboss/keycloak/themes/base/login/terms.ftl
      - ./keycloak-theme/messages_en.properties:/opt/jboss/keycloak/themes/base/login/messages/messages_en.properties
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: on-failure
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  ssl-service:
    image: certbot/certbot:v1.23.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    depends_on:
      - front-end
    command:
      - renew
      #- certonly
      #- --webroot
      #- -w
      #- /var/www/certbot/
      #- --email=uninabandi@libero.it
      #- --agree-tos
      #- --no-eff-email
      #- -d
      #- bandiunina.it



